name: CI Orchestrator

on:
  push:
    paths:
      - 'data/raw/train.csv'

jobs:
  train:
    permissions:
      contents: write
    uses: ./.github/workflows/train.yml

  test:
    needs: train
    permissions:
      contents: write
    uses: ./.github/workflows/test.yml
