# .github/workflows/ci.yml
name: CI Orchestrator

on:
  push:
    paths:
      - 'data/raw/train.csv'

jobs:
  train:
    uses: ./.github/workflows/train.yml

  test:
    needs: train
    uses: ./.github/workflows/test.yml