# .github/workflows/ci.yml
name: CI Orchestrator

on:
  push:
    paths:
      - 'data/raw/train.csv'

jobs:
  trigger-train:
    uses: ./.github/workflows/train.yml

  trigger-test:
    needs: trigger-train
    uses: ./.github/workflows/test.yml