name: Retrain Model on New Data

on:
  push:
    paths:
      - 'data/raw/train.csv'

jobs:
  retrain-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python src/train_model.py

      - name: Commit Updated Models
        id: git-commit
        run: |
          # Set Git identity
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Stage model files
          git add models/*

          # Check if there are changes to commit
          if git diff --cached --exit-code; then
            echo "No model changes detected. Skipping commit."
          else
            git commit -m "Auto-update models and metrics after retraining"
            git push origin HEAD:main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}