name: Retrain Model on New Data
on:
    push:
        paths:
            - 'data/raw/train.csv'

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write  # Allow the job to push changes back to the repository

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'

            - name: Install dependencies
              run: |
                pip install -r requirements.txt

            - name: Run training script
              run: |
                python src/train.py

            - name: Commit and push changes
              uses: stefanzweifel/git-auto-commit-action@v5
    