name: Retrain Model on New Data

on:
  push:
    paths:
      - 'data/raw/train.csv'
  pull_request:
    paths:
      - 'data/raw/train.csv'

jobs:
  retrain-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: 
          pip install -r requirements.txt

      - name: Run Training Script
        run: 
          python src/train_model.py
        
      - name: Commit Updated Models
        env:
          NAME: ${{ secrets.USER_NAME }}
          EMAIL: ${{ secrets.USER_EMAIL }}
        run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL