name: Commit Updated Models

on:
  workflow_dispatch:
  workflow_call:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update trained models"
          file_pattern: "models/**"
