name: Retrain Model on New Data

on:
  workflow_dispatch:  # still allows manual triggering
  workflow_call:      # allows being used via `uses:`

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training script
        run: python src/train_model.py
